### ISSUE TITLE
rename some folders

### ISSUE THREAD

**Issue by hainm** [Amber-MD/pymsmt#5]
looking at pymsmt repo, I don't know what is the main folder to look at.

And you might want to change name too.
pymsmtapi --> api
pymsmtlib --> lib
pymsmtmol --> msmtmol

You can look at parmed to see how @swails organize his package.
https://github.com/ParmEd/ParmEd

**Comment by pengfeili1** [comment]
Hi Hai, thanks for your suggestion, the folder names have been changed.

**Comment by hainm** [comment]
@pengfeili1 

how many packages in pymsmt? are they independent? `parmed` has problem before: its name is `parmed` but it uses `chemistry` for importing. And Jason needed to rename his package, which is very good decision. (https://github.com/ParmEd/ParmEd/issues/85).

For example (from your api.py file):
currently `from chemistry.amber.readparm import AmberParm`

with new `parmed` package:
```python
import parmed as pmd
```
Ideally, you should organize your package like scipy

`from scipy import special, optimize`

So with `pymsmt`

```python
import pymsmt
from pymsmt import lib
from pymsmt import api
from pymsmt.mcpb import resp_fitting
...
```

**Comment by hainm** [comment]
and do you have any intention to change `pymsmt` name? it's not really descriptive IMO. Like `ParmEd` --> Parmed Editor. 

and what's `mcpb` and so on?

**Comment by swails** [comment]
This is all described in the Amber 15 manual -- chapter 15.8 on page 282.  It's the Python Metal Site Modeling Toolbox, which is a satisfactory name IMO.  Likewise, MCPB is the metal center parameter builder, and has been called that for ~5 years now.

At this point changing MCPB would be a mistake (since `MCPB.py` is replacing the MTK++-based `MCPB` program), and MSMT is a perfectly reasonable acronym for this project.

**Comment by hainm** [comment]
>  Likewise, MCPB is the metal center parameter builder, and has been called that for ~5 years now.

Oh, I don't know this. You're right. thanks.
