### ISSUE TITLE
parmed and pymsmt overlap

### ISSUE THREAD

**Issue by hainm** [Amber-MD/pymsmt#8]
I see some overlap functions between ParmEd and pymsmt, what do you think about just import from `ParmEd`? (such as for load mol2 file `load_file('your.mol2')`?

The overall ideas is to build Amber as an ecosystem and each package does its best for what it focuses on. `ParmEd` is very well tested and developed at fast speed, and it's specially designed for Topology editing, parsing, ...

https://github.com/Amber-MD/pymsmt/blob/c8e04afaa1d3003065430701f7402f666fe269c3/msmtmol/readmol2.py

My point here is to let ParmEd do the parsin and pymsmt can focus on its aim.

**Comment by pengfeili1** [comment]
Hi Hai,

Thanks for the suggestion. Yeah, I agree that ParmEd would be fast to read or write files. But due to pymsmt is just designed for parameter buildings about metal containing systems, it is not eager for the high speed performance now. I checked the mol2 parser in ParmEd, and did not find very similar data structure I am using for the molecule in pymsmt now. I plan to add more modules/functions into pymsmt, which may be designed that could use pymsmt standalone. Using ParmEd’s mol2 parser may not convenient for user’ using (they need to download ParmEd and pymsmt at the same time and due to the code's fast development, compatibility issue may cause problem). So I will just keep the mol2 parser in pymsmt now and if needed (e.g. need high speed reading and writing) I will consider to use the ParmEd's one in the future.

Best,
Pengfei

**Comment by hainm** [comment]
> I checked the mol2 parser in ParmEd, and did not find very similar data structure I am using for the molecule in pymsmt now. I plan to add more modules/functions into pymsmt, which may be designed that could use pymsmt standalone.

yeah, make sense.
